### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by statik** [kevinslin/cdk-constants#1]
Hi! I love the idea of this library, thank you for making it.

I ran into an error trying to install:
```
> npm i cdk-constants@1.0.6                                   
npm WARN cdk@0.1.0 No repository field.
npm WARN cdk@0.1.0 No license field.

npm ERR! path /Users/emurphy/kindlyops/kindlyops/cdk/node_modules/cdk-constants/lib/bin/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/emurphy/kindlyops/kindlyops/cdk/node_modules/cdk-constants/lib/bin/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Is there any extra info I can provide to help figure out why this isn't installing?

**Comment by justin8** [comment]
same here

**Comment by kevinslin** [comment]
just took a look. you were getting the issue because the cli used to generate this library was accidentally included in this package (its used to generate some of the constants but not included in the constants library to reduce the build size). just pushed a new version to npm (note that there has been a major version bump to correct a typo, `principles` -> `principals`
